[build]
      builder = "DOCKERFILE"
      dockerfilePath = "Dockerfile"
    
    [deploy]
      startCommand = "node server.js"
      healthcheckPath = ""
      restartPolicyType = "on_failure"
      replicaCount = 1
